---
- hosts: all
  connection: local

  tasks:
  - name: Create security group
    local_action:
      module: ec2_group
      name: MoodleSecurityGroup
      description: Access MoodleSecurityGroup
      region: sa-east-1
      vpc_id: vpc-e4962981
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
          
  - name: create ec2 instance
    action: 
      module: ec2
      zone: sa-east-1a
      image: ami-8737829a
      instance_type: t2.micro
      state: present
      region: sa-east-1
      key_name: AmazonKeyValue
      vpc_subnet_id: vpc-e4921349
      group: MoodleSecurityGroup
      wait: yes
    register: ec2
    
  - name: Add instances to host group
    local_action: add_host hostname= groupname=MoodleSecurityGroup
    with_items: ec2.instance
    
  - name: Tag instances
    local_action: ec2_tag resource= region=sa-east-1 state=present
    with_items: ec2.instances
    args:
      tags:
        Name: Moodle
    
  - name: Give everyone one minute
    pause: minutes=1
