---
- hosts: all
  connection: local
  remote_user: ec2-user
  sudo: yes

  tasks:
  - name: Create security group
    local_action:
      module: ec2_group
      name: MoodleSecurityGroup
      description: MyMoodleSecurityGroup
      region: sa-east-1
      vpc_id: vpc-e4962981
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
          
  - name: create ec2 instance
    action: 
      module: ec2
      zone: sa-east-1a
      image: ami-8737829a
      instance_type: t2.micro
      state: present
      region: sa-east-1
      key_name: AmazonKeyValue
      vpc_subnet_id: vpc-e4921349
      group: MoodleSecurityGroup
      wait: yes
    register: ec2
    
  - name: Add instances to host group
    action: add_host hostname={{item.public_ip}} groupname=MoodleSecurityGroup
    with_items: ec2.instances
    
  - name: Add tag to instances
    local_action: ec2_tag resource={{item.id}} region=sa-east-1 state=present
    with_items: ec2.instances
    args:
      tags:
        Name: MoodleServer
  
  - name: Adding server to inventory
    local_action: shell echo "[MoodleServer]\n{{item.public_ip}}" >> hosts chdir=/etc/ansible/
    with_items: ec2.instances
    
  - name: Give everyone one minute
    pause: minutes=1
