---
- hosts: all
  connection: local

  tasks:
  - name: create ec2 instance
    action: 
      module: ec2
      aws_access_key: utong
      aws_secret_key: utong2
      zone: sa-east-1a
      image: ami-8737829a
      instance_type: t2.micro
      state: present
      region: sa-east-1
      key_name: AmazonKeyValue
      vpc_subnet_id: vpc-e4921349
      group: sg-aaaaa2222
      instance_tags: 
        Name: FirstMOOCAnsible
