---
- name: Transfer and execute a script
  hosts: all
  user: root
  sudo: yes
  connection: local
  
  tasks:
  - name: Transfer the script
    src: LAMPMoodleScript.sh dest=/home/LAMPScript mode=0777
  - name: Execute the script
    command: sh /home/LAMPScript/LAMPMoodleScript.sh
